build: Filter out 'ADHOCBUILD-*' versions
1. Script adjusted to filter out ROCM_VERSION versions like:
- `ADHOCBUILD-7.0.0rc20250625`

Which would cause errors like:
'''
[INFO] Step 2: Setting up ROCm environment...
[INFO] Locating HIP device libraries (amdgcn/bitcode)...

Error: Process completed with exit code 1.
'''

2. Fix ROCm download stream
- https://rocm.nightlies.amd.com/tarball-multi-arch

Code changes related to the following:
  * build (shell) script

Signed-off-by: Oliveira, Daniel <daniel.oliveira@amd.com>